feat: add guess_config
stainless-api/upload-openapi-spec-action pull request #42
Opened 2024-08-13 17:56 UTC by cjquines

2024-08-13 18:02 UTC, meorphis commented
were you able to test this in prod? you can create a test repo to host your spec and add the github action like so:
```
jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stainless-api/upload-openapi-spec-action@{your branch's SHA}
```

2024-08-13 18:04 UTC, cjquines commented
how fast does prod update? i ran an action (https://github.com/stainless-sdks/cjquines-source/actions/runs/10374835174/job/28723176533) but it doesn't look like it did the thing

2024-08-13 21:50 UTC, cjquines commented
ok cool, here's [action run](https://github.com/stainless-sdks/cjquines-source/actions/runs/10377728098/job/28732540674) and [corresponding commit](https://github.com/stainless-sdks/cjquines-config/commit/6bcddfd4cf9fc463d7893019bd62f95f6467af97)

2024-08-15 16:50 UTC, meorphis approved these changes

2024-08-15 16:55 UTC, meorphis commented on README.md
> +`guess_config` is an optional parameter that, when `true`, will regenerate the endpoints in the Stainless config file. By default, it is `false`.
actually maybe something like:

> `guess_config` is an optional parameter that, when `true`, will update your Stainless config file based on the change you've made to your spec. By default, it is `false`. You should not set this to `true` if you are passing a `config_path`.

2024-08-15 16:56 UTC, meorphis requested changes
left one more comment inline

2024-08-15 18:40 UTC, cjquines commented
responded to comment; also figured out why [this commit](https://github.com/stainless-sdks/cjquines-config/commit/6bcddfd4cf9fc463d7893019bd62f95f6467af97) was weird; the fix was stainless-api/stainless#6430. here's a new [app run](https://github.com/stainless-sdks/cjquines-source/actions/runs/10408781887) and [commit](https://github.com/stainless-sdks/cjquines-prod-0-config/commit/8ad6b6780d53e8c0e0fff4d7dbf18673236fd6fd), which should look better now

2024-08-15 18:53 UTC, meorphis approved these changes

2024-08-15 19:02 UTC, merged